import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('electronAPI', {
  listClients:     (rootPath: string) => ipcRenderer.invoke('fs:listClients', rootPath),
  listDocs:        (clientPath: string) => ipcRenderer.invoke('fs:listDocs', clientPath),
  readPdf:         (filePath: string) => ipcRenderer.invoke('fs:readPdf', filePath),
  saveAnnotations: (pdfPath: string, annotations: unknown) => ipcRenderer.invoke('fs:saveAnnotations', pdfPath, annotations),
  moveFile:        (srcPath: string, destFolder: string) => ipcRenderer.invoke('fs:moveFile', srcPath, destFolder),
  renameFile:      (filePath: string, newName: string) => ipcRenderer.invoke('fs:renameFile', filePath, newName),
  getAnnotations:  (pdfPath: string) => ipcRenderer.invoke('fs:getAnnotations', pdfPath),
  combineFiles:    (topPath: string, bottomPath: string) => ipcRenderer.invoke('fs:combineFiles', topPath, bottomPath),
  pickScanner:     () => ipcRenderer.invoke('fs:pickScanner'),
  getScanInbox:    () => ipcRenderer.invoke('fs:getScanInbox'),
  startScan:        (destFolder: string, useNativeUI: boolean, dpi?: number, colorMode?: string) => ipcRenderer.invoke('fs:startScan', destFolder, useNativeUI, dpi, colorMode),
  listScanDevices:  () => ipcRenderer.invoke('fs:listScanDevices'),
  stopScanWatcher:  () => ipcRenderer.invoke('fs:stopScanWatcher'),
  onScanFile:       (cb: (data: {name:string}) => void) => ipcRenderer.on('scan:fileArrived', (_e, data) => cb(data)),
  onScanError:      (cb: (err: string) => void) => ipcRenderer.on('scan:error', (_e, err) => cb(err)),
  onScanProgress:   (cb: (data: {page:number}) => void) => ipcRenderer.on('scan:progress', (_e, data) => cb(data)),
  pickFolder:      () => ipcRenderer.invoke('fs:pickFolder'),
  deleteFile:      (p:string) => ipcRenderer.invoke('fs:deleteFile', p),
  copyFile:        (p:string) => ipcRenderer.invoke('fs:copyFile', p),
  savePdf:         (p:string, b:ArrayBuffer) => ipcRenderer.invoke('fs:savePdf', p, b),
  renameFolder:    (p:string, n:string) => ipcRenderer.invoke('fs:renameFolder', p, n),
  getConfig:       (k:string) => ipcRenderer.invoke('fs:getConfig', k),
  setConfig:       (k:string, v:unknown) => ipcRenderer.invoke('fs:setConfig', k, v),
  printFile:       (p:string) => ipcRenderer.invoke('fs:printFile', p),
  printBytes:      (b:ArrayBuffer) => ipcRenderer.invoke('fs:printBytes', b),
  minimizeWindow:  () => ipcRenderer.send('win:minimize'),
  maximizeWindow:  () => ipcRenderer.send('win:maximize'),
  closeWindow:     () => ipcRenderer.send('win:close'),
})
